version: "3.9"

services:
  webapp:
    build:
      context: ./main
      target: webapp
    ports:
      - "1337:1337"
    depends_on:
      - mongodb
    networks:
      - app_network
    environment:
      NODE_ENV: "development"
      MONGODB_URI: "mongodb://mongodb:27017/bengine"
      SESSION_SECRET: "wwwwhahahaatatatateverrrrrrr"
    restart: unless-stopped

  job_runner:
    build:
      context: ./main
      target: job_runner
    depends_on:
      - mongodb
    networks:
    - app_network
    environment:
      NODE_ENV: "development"
    restart: unless-stopped

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    networks:
      - app_network
    volumes:
      - mongodb_data:/data/db

  manager:
    build: ./services/manager
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - openai
    networks:
      - app_network
    env_file:
      - .env

  openai:
    build: ./services/openai
    ports:
      - "3001:3001"
    networks:
      - app_network
    env_file:
      - .env

  web:
    build: ./services/web
    ports:
      - "3002:3002"
    networks:
      - app_network
    env_file:
      - .env

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:

volumes:
  mongodb_data: