version: '3.8'

services:
  webapp:
    build:
      context: .
      target: webapp
    ports:
      - "1337:1337"
    restart: unless-stopped

  job_runner:
    build:
      context: .
      target: job_runner
    restart: unless-stopped
