version: '3.8'

services:
  bengine-app:
    build:
      context: .
      target: bengine-app
    ports:
      - "1337:1337"
    restart: unless-stopped
    networks: 
      - bengine-main

  bengine-job-runner:
    build:
      context: .
      target: bengine-job-runner
    restart: unless-stopped
    networks: 
      - bengine-main

networks:
  bengine-main:
