version: "3.9"

services:
  bengine-manager:
    build: ./manager
    ports:
      - "3000:3000"
    depends_on:
      - bengine-redis
    networks:
      - bengine-services

  bengine-redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - bengine-services

networks:
  bengine-services:

