version: "3.9"

services:
  manager:
    build: ./manager
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:

